### PR TITLE
Add Build PCMan Wiki Link to Readme

### PR DESCRIPTION
**Pull request by name2name2**
Add Build PCMan Wiki Link to Readme

### CODE REVIEW

**Comment by name2name2** [comment]
AppVeyor build failed，可以幫忙檢查一下嗎

**Comment by name2name2** [comment]
AppVeyor 建置出線錯誤： `fatal error C1083: Cannot open include file: 'boost/asio/ssl.hpp': No such file or directory`

**Comment by holishing** [comment]
這是 #49 要解決的

**Comment by name2name2** [comment]
close because build error

**Pull request closed without merging**
